package com.fepdf.fepdf.vista;

import com.toedter.calendar.JDateChooser;
import java.awt.Toolkit;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author GL
 */
public class MainFrame extends javax.swing.JFrame {
    

    public MainFrame() {
        initComponents();
    }

    public JButton getBtnFin() {
        return btnFin;
    }

    public JTextField getCampoA1() {
        return campoA1;
    }

    public JTextField getCampoA2() {
        return campoA2;
    }

    public JTextField getCampoNombres() {
        return campoNombres;
    }

    public JTextField getCampoEC() {
        return campoEC;
    }

    public JTextField getCampoNacio() {
        return campoNacio;
    }

    public JTextField getCampoDNI() {
        return campoDNI;
    }

    public JTextField getCampoCalle() {
        return campoCalle;
    }

    public JTextField getCampoCiudad() {
        return campoCiudad;
    }

    public JTextField getCampoPais() {
        return campoPais;
    }

    public JTextField getCampoProvincia() {
        return campoProvincia;
    }

    public JTextField getCampoEmail() {
        return campoEmail;
    }

    public JTextField getCampoTelefono() {
        return campoTelefono;
    }

    public JDateChooser getCampoFN() {
        return campoFN;
    }

    public JTextField getCampoConsulado() {
        return campoConsulado;
    }
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlSuperior = new javax.swing.JPanel();
        txtPnlSuperior = new javax.swing.JLabel();
        logoEmpresa = new javax.swing.JLabel();
        pnlCentral = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        campoNombres = new javax.swing.JTextField();
        lblA1 = new javax.swing.JLabel();
        campoA1 = new javax.swing.JTextField();
        lblA2 = new javax.swing.JLabel();
        campoA2 = new javax.swing.JTextField();
        lblEC = new javax.swing.JLabel();
        campoEC = new javax.swing.JTextField();
        lblNacio = new javax.swing.JLabel();
        campoNacio = new javax.swing.JTextField();
        lblDNI = new javax.swing.JLabel();
        campoDNI = new javax.swing.JTextField();
        lblCalle = new javax.swing.JLabel();
        campoCalle = new javax.swing.JTextField();
        lblCiudad = new javax.swing.JLabel();
        campoCiudad = new javax.swing.JTextField();
        lblProvincia = new javax.swing.JLabel();
        campoProvincia = new javax.swing.JTextField();
        lblPais = new javax.swing.JLabel();
        campoPais = new javax.swing.JTextField();
        lblTelefono = new javax.swing.JLabel();
        campoTelefono = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        campoEmail = new javax.swing.JTextField();
        labelFn = new javax.swing.JLabel();
        campoFN = new com.toedter.calendar.JDateChooser();
        lblConsulado = new javax.swing.JLabel();
        campoConsulado = new javax.swing.JTextField();
        btnFin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FEPDF - Version 1.0");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imgs/logo-fe2.jpg")));
        setPreferredSize(new java.awt.Dimension(800, 400));
        setResizable(false);

        pnlSuperior.setBackground(new java.awt.Color(66, 118, 202));
        pnlSuperior.setPreferredSize(new java.awt.Dimension(0, 50));
        pnlSuperior.setLayout(new java.awt.BorderLayout());

        txtPnlSuperior.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        txtPnlSuperior.setForeground(new java.awt.Color(255, 255, 255));
        txtPnlSuperior.setText("FEPDF");
        pnlSuperior.add(txtPnlSuperior, java.awt.BorderLayout.EAST);

        logoEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/logo-fe2.jpg"))); // NOI18N
        pnlSuperior.add(logoEmpresa, java.awt.BorderLayout.WEST);

        getContentPane().add(pnlSuperior, java.awt.BorderLayout.NORTH);

        lblNombre.setText("Nombre(s)");

        lblA1.setText("Apellido Paterno");

        lblA2.setText("Apellido Materno");

        lblEC.setText("Estado Civil");

        lblNacio.setText("Nacionalidad");

        lblDNI.setText("DNI");

        lblCalle.setText("Calle (c/altura)");

        lblCiudad.setText("Ciudad");

        lblProvincia.setText("Provincia");

        lblPais.setText("Pais");

        campoPais.setPreferredSize(new java.awt.Dimension(200, 22));

        lblTelefono.setText("Telefono");

        lblEmail.setText("Email");

        labelFn.setText("Fecha de Nacimiento");

        campoFN.setDateFormatString("dd/MM/yyyy");

        lblConsulado.setText("Consulado");

        btnFin.setText("Finalizar");

        javax.swing.GroupLayout pnlCentralLayout = new javax.swing.GroupLayout(pnlCentral);
        pnlCentral.setLayout(pnlCentralLayout);
        pnlCentralLayout.setHorizontalGroup(
            pnlCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCentralLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(pnlCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCentralLayout.createSequentialGroup()
                        .addGroup(pnlCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblA2)
                            .addComponent(lblNombre)
                            .addComponent(lblEC)
                            .addComponent(lblCalle)
                            .addComponent(lblProvincia)
                            .addComponent(lblTelefono))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(campoNombres, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(campoA2)
                            .addComponent(campoEC)
                            .addComponent(campoCalle)
                            .addComponent(campoProvincia)
                            .addComponent(campoTelefono)))
                    .addGroup(pnlCentralLayout.createSequentialGroup()
                        .addComponent(labelFn)
                        .addGap(18, 18, 18)
                        .addComponent(campoFN, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pnlCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCentralLayout.createSequentialGroup()
                        .addGroup(pnlCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCiudad)
                            .addComponent(lblPais)
                            .addComponent(lblEmail))
                        .addContainerGap(425, Short.MAX_VALUE))
                    .addGroup(pnlCentralLayout.createSequentialGroup()
                        .addGroup(pnlCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlCentralLayout.createSequentialGroup()
                                .addComponent(lblConsulado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                                .addComponent(campoConsulado, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(pnlCentralLayout.createSequentialGroup()
                                    .addGroup(pnlCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblA1)
                                        .addComponent(lblDNI)
                                        .addComponent(lblNacio))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(pnlCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(campoNacio, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                        .addComponent(campoDNI)
                                        .addComponent(campoA1)))
                                .addComponent(campoCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(campoPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(campoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 169, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCentralLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnFin)
                .addGap(21, 21, 21))
        );
        pnlCentralLayout.setVerticalGroup(
            pnlCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCentralLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pnlCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCentralLayout.createSequentialGroup()
                        .addGroup(pnlCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombre)
                            .addComponent(campoNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblA1)
                            .addComponent(campoA1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoA2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblA2)
                            .addComponent(campoDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDNI))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEC)
                            .addComponent(campoEC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(campoNacio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblNacio)))
                .addGap(9, 9, 9)
                .addGroup(pnlCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCalle)
                    .addComponent(campoCalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCiudad)
                    .addComponent(campoCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProvincia)
                    .addComponent(campoProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPais)
                    .addComponent(campoPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefono)
                    .addComponent(campoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmail)
                    .addComponent(campoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblConsulado)
                        .addComponent(labelFn)
                        .addComponent(campoConsulado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(campoFN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(btnFin)
                .addGap(18, 18, 18))
        );

        getContentPane().add(pnlCentral, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFin;
    private javax.swing.JTextField campoA1;
    private javax.swing.JTextField campoA2;
    private javax.swing.JTextField campoCalle;
    private javax.swing.JTextField campoCiudad;
    private javax.swing.JTextField campoConsulado;
    private javax.swing.JTextField campoDNI;
    private javax.swing.JTextField campoEC;
    private javax.swing.JTextField campoEmail;
    private com.toedter.calendar.JDateChooser campoFN;
    private javax.swing.JTextField campoNacio;
    private javax.swing.JTextField campoNombres;
    private javax.swing.JTextField campoPais;
    private javax.swing.JTextField campoProvincia;
    private javax.swing.JTextField campoTelefono;
    private javax.swing.JLabel labelFn;
    private javax.swing.JLabel lblA1;
    private javax.swing.JLabel lblA2;
    private javax.swing.JLabel lblCalle;
    private javax.swing.JLabel lblCiudad;
    private javax.swing.JLabel lblConsulado;
    private javax.swing.JLabel lblDNI;
    private javax.swing.JLabel lblEC;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblNacio;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPais;
    private javax.swing.JLabel lblProvincia;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel logoEmpresa;
    private javax.swing.JPanel pnlCentral;
    private javax.swing.JPanel pnlSuperior;
    private javax.swing.JLabel txtPnlSuperior;
    // End of variables declaration//GEN-END:variables
}
