package com.fepdf.fepdf.vista;

import com.toedter.calendar.JDateChooser;
import java.awt.Toolkit;
import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author GL
 */
public class MainFrame extends javax.swing.JFrame {
    

    public MainFrame() {
        initComponents();
    }

    public JButton getBtnFin() {
        return btnFin;
    }

    public JTextField getCampoA1() {
        return campoA1;
    }

    public JTextField getCampoA2() {
        return campoA2;
    }

    public JTextField getCampoNombres() {
        return campoNombres;
    }

    public JTextField getCampoNacio() {
        return campoNacio;
    }

    public JTextField getCampoDNI() {
        return campoDNI;
    }

    public JTextField getCampoCalle() {
        return campoCalle;
    }

    public JTextField getCampoCiudad() {
        return campoCiudad;
    }

    public JTextField getCampoPais() {
        return campoPais;
    }

    public JTextField getCampoProvincia() {
        return campoProvincia;
    }

    public JTextField getCampoEmail() {
        return campoEmail;
    }

    public JTextField getCampoTelefono() {
        return campoTelefono;
    }

    public JDateChooser getCampoFN() {
        return campoFN;
    }

    public JTextField getCampoConsulado() {
        return campoConsulado;
    }

    public JTextField getCampoCN() {
        return campoCN;
    }

    public JTextField getCampoPN() {
        return campoPN;
    }

    public JTextField getCampoPrN() {
        return campoPrN;
    }
    
    
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        pnlSuperior = new javax.swing.JPanel();
        txtPnlSuperior = new javax.swing.JLabel();
        logoEmpresa = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnlCentral = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        campoNombres = new javax.swing.JTextField();
        lblA1 = new javax.swing.JLabel();
        campoA1 = new javax.swing.JTextField();
        lblA2 = new javax.swing.JLabel();
        campoA2 = new javax.swing.JTextField();
        lblEC = new javax.swing.JLabel();
        lblNacio = new javax.swing.JLabel();
        campoNacio = new javax.swing.JTextField();
        lblDNI = new javax.swing.JLabel();
        campoDNI = new javax.swing.JTextField();
        lblCalle = new javax.swing.JLabel();
        campoCalle = new javax.swing.JTextField();
        lblCiudad = new javax.swing.JLabel();
        campoCiudad = new javax.swing.JTextField();
        lblProvincia = new javax.swing.JLabel();
        campoProvincia = new javax.swing.JTextField();
        lblPais = new javax.swing.JLabel();
        campoPais = new javax.swing.JTextField();
        lblTelefono = new javax.swing.JLabel();
        campoCN = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        campoEmail = new javax.swing.JTextField();
        labelFn = new javax.swing.JLabel();
        campoFN = new com.toedter.calendar.JDateChooser();
        lblConsulado = new javax.swing.JLabel();
        campoPrN = new javax.swing.JTextField();
        btnFin = new javax.swing.JButton();
        campoTelefono = new javax.swing.JTextField();
        lblCN = new javax.swing.JLabel();
        campoConsulado = new javax.swing.JTextField();
        lblPrN = new javax.swing.JLabel();
        campoPN = new javax.swing.JTextField();
        lblPN = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        comboSx = new javax.swing.JComboBox<>();
        labelFn1 = new javax.swing.JLabel();
        campoFT = new com.toedter.calendar.JDateChooser();
        lblME = new javax.swing.JLabel();
        campoME = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        campoPE = new javax.swing.JTextField();
        comboEC = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        comboEstudios = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        campoCP = new javax.swing.JTextField();
        pnlNacimiento = new javax.swing.JPanel();
        labelCheck12 = new javax.swing.JLabel();
        labelCheck13 = new javax.swing.JLabel();
        campoFI = new com.toedter.calendar.JDateChooser();
        labelCheck14 = new javax.swing.JLabel();
        campoRC = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        campoTomo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        campoPagina = new javax.swing.JTextField();
        lblNro = new javax.swing.JLabel();
        campoNroPag = new javax.swing.JTextField();
        campoHN = new javax.swing.JTextField();
        pnlProgenitores = new javax.swing.JPanel();
        containerDataPadre = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        campoNomP = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        campoApePadre1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        campoApePadre2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        campoPP = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        campoMP = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        campoNacP = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        comboEcNacP = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        comboEcAcP = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        nacioNacP = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        nacioAcP = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        domP = new javax.swing.JTextField();
        campoFNP = new com.toedter.calendar.JDateChooser();
        jLabel30 = new javax.swing.JLabel();
        containerDataMadre = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        campoNomM = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        campoApeMadre = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        campoApeMadre2 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        campoPM = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        campoMM = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        campoNacM = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        comboEcNacM = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        comboEcAcM = new javax.swing.JComboBox<>();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        nacioNacM = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        nacioAcM = new javax.swing.JTextField();
        campoFNM = new com.toedter.calendar.JDateChooser();
        jLabel31 = new javax.swing.JLabel();
        pnlNacimiento1 = new javax.swing.JPanel();
        labelCheck30 = new javax.swing.JLabel();
        combo1 = new javax.swing.JComboBox<>();
        jLabel32 = new javax.swing.JLabel();
        fechaMatri = new com.toedter.calendar.JDateChooser();
        lblLugar = new javax.swing.JLabel();
        campoLugar = new javax.swing.JTextField();
        lblLugar1 = new javax.swing.JLabel();
        inscripcion = new javax.swing.JTextField();
        pnlContacto = new javax.swing.JPanel();
        labelCheck2 = new javax.swing.JLabel();
        campoNC = new javax.swing.JTextField();
        labelCheck3 = new javax.swing.JLabel();
        campoDC1 = new javax.swing.JTextField();
        labelCheck4 = new javax.swing.JLabel();
        campoTC1 = new javax.swing.JTextField();
        labelCheck5 = new javax.swing.JLabel();
        campoNC2 = new javax.swing.JTextField();
        labelCheck6 = new javax.swing.JLabel();
        campoDC2 = new javax.swing.JTextField();
        labelCheck7 = new javax.swing.JLabel();
        campoTC2 = new javax.swing.JTextField();
        labelCheck8 = new javax.swing.JLabel();
        campoCony = new javax.swing.JTextField();
        pnlHijos = new javax.swing.JPanel();
        labelCheck9 = new javax.swing.JLabel();
        campoNH1 = new javax.swing.JTextField();
        labelCheck10 = new javax.swing.JLabel();
        campoLNH1 = new javax.swing.JTextField();
        labelCheck11 = new javax.swing.JLabel();
        campoFNH1 = new com.toedter.calendar.JDateChooser();
        campoNH2 = new javax.swing.JTextField();
        labelCheck16 = new javax.swing.JLabel();
        labelCheck17 = new javax.swing.JLabel();
        campoLNH2 = new javax.swing.JTextField();
        campoFNH2 = new com.toedter.calendar.JDateChooser();
        labelCheck18 = new javax.swing.JLabel();
        labelCheck19 = new javax.swing.JLabel();
        campoNH3 = new javax.swing.JTextField();
        campoLNH3 = new javax.swing.JTextField();
        labelCheck20 = new javax.swing.JLabel();
        labelCheck21 = new javax.swing.JLabel();
        campoFNH3 = new com.toedter.calendar.JDateChooser();
        labelCheck22 = new javax.swing.JLabel();
        campoNH4 = new javax.swing.JTextField();
        labelCheck23 = new javax.swing.JLabel();
        campoLNH4 = new javax.swing.JTextField();
        campoFNH4 = new com.toedter.calendar.JDateChooser();
        labelCheck24 = new javax.swing.JLabel();
        labelCheck25 = new javax.swing.JLabel();
        campoNH5 = new javax.swing.JTextField();
        labelCheck26 = new javax.swing.JLabel();
        campoLNH5 = new javax.swing.JTextField();
        labelCheck27 = new javax.swing.JLabel();
        campoFNH5 = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FEPDF - Version 1.2");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imgs/logo-fe2.jpg")));
        setResizable(false);

        pnlSuperior.setBackground(new java.awt.Color(66, 118, 202));
        pnlSuperior.setPreferredSize(new java.awt.Dimension(0, 50));
        pnlSuperior.setLayout(new java.awt.BorderLayout());

        txtPnlSuperior.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        txtPnlSuperior.setForeground(new java.awt.Color(255, 255, 255));
        txtPnlSuperior.setText("FEPDF");
        pnlSuperior.add(txtPnlSuperior, java.awt.BorderLayout.EAST);

        logoEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/logo-fe2.jpg"))); // NOI18N
        pnlSuperior.add(logoEmpresa, java.awt.BorderLayout.WEST);

        getContentPane().add(pnlSuperior, java.awt.BorderLayout.NORTH);

        lblNombre.setText("Nombre(s)");

        campoNombres.setPreferredSize(new java.awt.Dimension(200, 23));

        lblA1.setText("Apellido Paterno");

        campoA1.setPreferredSize(new java.awt.Dimension(200, 23));

        lblA2.setText("Apellido Materno");

        campoA2.setMinimumSize(new java.awt.Dimension(200, 23));
        campoA2.setPreferredSize(new java.awt.Dimension(200, 23));

        lblEC.setText("Estado Civil");

        lblNacio.setText("Nacionalidad");

        campoNacio.setPreferredSize(new java.awt.Dimension(200, 23));

        lblDNI.setText("DNI");

        campoDNI.setPreferredSize(new java.awt.Dimension(200, 23));

        lblCalle.setText("Calle (c/altura)");

        campoCalle.setPreferredSize(new java.awt.Dimension(200, 23));

        lblCiudad.setText("Ciudad");

        campoCiudad.setPreferredSize(new java.awt.Dimension(200, 23));

        lblProvincia.setText("Provincia");

        campoProvincia.setPreferredSize(new java.awt.Dimension(100, 23));

        lblPais.setText("Pais");

        campoPais.setPreferredSize(new java.awt.Dimension(200, 22));

        lblTelefono.setText("Telefono");

        campoCN.setPreferredSize(new java.awt.Dimension(200, 23));

        lblEmail.setText("Email");

        campoEmail.setPreferredSize(new java.awt.Dimension(200, 23));

        labelFn.setText("Fecha de Nacimiento");

        campoFN.setDateFormatString("dd/MM/yyyy");

        lblConsulado.setText("Consulado");

        campoPrN.setPreferredSize(new java.awt.Dimension(200, 23));

        btnFin.setText("Finalizar");

        campoTelefono.setText("+54 9");
        campoTelefono.setPreferredSize(new java.awt.Dimension(200, 23));

        lblCN.setText("Ciudad de Nacimiento");

        campoConsulado.setPreferredSize(new java.awt.Dimension(200, 23));

        lblPrN.setText("Provincia de Nacimiento");

        campoPN.setPreferredSize(new java.awt.Dimension(200, 23));

        lblPN.setText("Pais de Nacimiento");

        jLabel1.setText("Sexo");

        comboSx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino" }));
        comboSx.setPreferredSize(new java.awt.Dimension(150, 23));

        labelFn1.setText("Fecha del Turno");

        campoFT.setDateFormatString("dd/MM/yyyy");

        lblME.setText("Municipio Español");

        campoME.setPreferredSize(new java.awt.Dimension(200, 23));

        jLabel2.setText("Provincia Española");

        campoPE.setPreferredSize(new java.awt.Dimension(200, 23));

        comboEC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Soltero", "Casado", "Divorciado", "Viudo", "Separado" }));
        comboEC.setPreferredSize(new java.awt.Dimension(200, 23));

        jLabel3.setText("Estudios");

        comboEstudios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Primaria / Secundaria", "Terciario", "Universitario", "No Consta", " " }));
        comboEstudios.setPreferredSize(new java.awt.Dimension(200, 23));

        jLabel4.setText("CP");

        javax.swing.GroupLayout pnlCentralLayout = new javax.swing.GroupLayout(pnlCentral);
        pnlCentral.setLayout(pnlCentralLayout);
        pnlCentralLayout.setHorizontalGroup(
            pnlCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCentralLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(pnlCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCentralLayout.createSequentialGroup()
                        .addGroup(pnlCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlCentralLayout.createSequentialGroup()
                                .addGroup(pnlCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblA2)
                                    .addComponent(lblNombre)
                                    .addComponent(lblEC)
                                    .addComponent(lblCalle)
                                    .addComponent(lblProvincia)
                                    .addComponent(lblTelefono))
                                .addGap(36, 36, 36)
                                .addGroup(pnlCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(campoNombres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campoA2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campoCalle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campoTelefono, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comboEC, 0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnlCentralLayout.createSequentialGroup()
                                        .addComponent(campoProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(campoCP, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(pnlCentralLayout.createSequentialGroup()
                                .addGroup(pnlCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelFn)
                                    .addComponent(labelFn1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoFT, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campoFN, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addGroup(pnlCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlCentralLayout.createSequentialGroup()
                                .addGroup(pnlCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblA1)
                                    .addComponent(lblDNI)
                                    .addComponent(lblNacio))
                                .addGap(48, 48, 48)
                                .addGroup(pnlCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(campoDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campoNacio, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campoA1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnlCentralLayout.createSequentialGroup()
                                .addGroup(pnlCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblConsulado)
                                    .addComponent(lblEmail)
                                    .addComponent(lblPais)
                                    .addComponent(lblCiudad)
                                    .addComponent(jLabel1)
                                    .addGroup(pnlCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblPrN, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblME))
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comboSx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campoCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campoPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campoConsulado, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campoPrN, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campoME, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comboEstudios, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(102, Short.MAX_VALUE))
                    .addGroup(pnlCentralLayout.createSequentialGroup()
                        .addGroup(pnlCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlCentralLayout.createSequentialGroup()
                                .addComponent(lblCN)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoCN, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(pnlCentralLayout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(campoPE, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pnlCentralLayout.createSequentialGroup()
                                    .addComponent(lblPN)
                                    .addGap(18, 18, 18)
                                    .addComponent(campoPN, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnFin)
                        .addGap(21, 21, 21))))
        );
        pnlCentralLayout.setVerticalGroup(
            pnlCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCentralLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pnlCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCentralLayout.createSequentialGroup()
                        .addGroup(pnlCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoA1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblNombre)
                                .addComponent(campoNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblA1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoA2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblA2)
                            .addComponent(lblDNI))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEC)
                            .addComponent(comboEC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCentralLayout.createSequentialGroup()
                        .addComponent(campoDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoNacio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNacio))))
                .addGap(9, 9, 9)
                .addGroup(pnlCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCalle)
                    .addComponent(campoCalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCiudad)
                    .addComponent(campoCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProvincia)
                    .addComponent(campoProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPais)
                    .addComponent(campoPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(campoCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefono)
                    .addComponent(lblEmail)
                    .addComponent(campoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCentralLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelFn)
                            .addComponent(campoFN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlCentralLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(pnlCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboSx, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblConsulado)
                                .addComponent(campoConsulado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelFn1))
                            .addComponent(campoFT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(9, 9, 9)
                .addGroup(pnlCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCN)
                    .addComponent(campoCN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrN)
                    .addComponent(campoPrN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPN)
                    .addComponent(campoPN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblME)
                    .addComponent(campoME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCentralLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(campoPE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(comboEstudios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCentralLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnFin)
                        .addContainerGap())))
        );

        jTabbedPane1.addTab("Datos Persona", pnlCentral);

        labelCheck12.setText("Hora del Nacimiento");

        labelCheck13.setText("Fecha de Inscripcion");

        campoFI.setDateFormatString("dd/MM/yyyy");
        campoFI.setPreferredSize(new java.awt.Dimension(150, 23));

        labelCheck14.setText("Registro Civil");

        campoRC.setPreferredSize(new java.awt.Dimension(200, 23));

        jLabel5.setText("Tomo");

        jLabel6.setText("Pagina");

        lblNro.setText("Nro");

        campoHN.setText("00:00");

        javax.swing.GroupLayout pnlNacimientoLayout = new javax.swing.GroupLayout(pnlNacimiento);
        pnlNacimiento.setLayout(pnlNacimientoLayout);
        pnlNacimientoLayout.setHorizontalGroup(
            pnlNacimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNacimientoLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(pnlNacimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCheck12)
                    .addComponent(labelCheck14))
                .addGroup(pnlNacimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlNacimientoLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(campoRC, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlNacimientoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(campoHN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23)
                .addGroup(pnlNacimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlNacimientoLayout.createSequentialGroup()
                        .addComponent(labelCheck13)
                        .addGap(18, 18, 18)
                        .addComponent(campoFI, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlNacimientoLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campoTomo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campoPagina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblNro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campoNroPag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        pnlNacimientoLayout.setVerticalGroup(
            pnlNacimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNacimientoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pnlNacimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlNacimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelCheck12)
                        .addComponent(campoHN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(campoFI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCheck13))
                .addGap(18, 18, 18)
                .addGroup(pnlNacimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlNacimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblNro)
                        .addComponent(campoNroPag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlNacimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(campoPagina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlNacimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelCheck14)
                        .addComponent(campoRC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(campoTomo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(429, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Datos del Nacimiento", pnlNacimiento);

        containerDataPadre.setBorder(javax.swing.BorderFactory.createTitledBorder("Padre"));

        jLabel7.setText("Nombre");

        campoNomP.setPreferredSize(new java.awt.Dimension(160, 23));

        jLabel8.setText("Apellido 1");

        campoApePadre1.setPreferredSize(new java.awt.Dimension(160, 23));

        jLabel9.setText("Apellido 2");

        campoApePadre2.setPreferredSize(new java.awt.Dimension(160, 23));

        jLabel10.setText("Padre");

        campoPP.setPreferredSize(new java.awt.Dimension(160, 23));

        jLabel11.setText("Madre");

        campoMP.setPreferredSize(new java.awt.Dimension(160, 23));

        jLabel12.setText("Nacido en");

        campoNacP.setPreferredSize(new java.awt.Dimension(245, 23));

        jLabel13.setText("E.C al nacer el hijo");

        comboEcNacP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Soltero", "Casado", "Divorciado", "Viudo" }));
        comboEcNacP.setPreferredSize(new java.awt.Dimension(96, 23));

        jLabel14.setText("E.C actual");

        comboEcAcP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Soltero", "Casado", "Divorciado", "Viudo", "Fallecido" }));
        comboEcAcP.setPreferredSize(new java.awt.Dimension(96, 23));

        jLabel16.setText("Nacionalidad al nacer el hijo");

        nacioNacP.setPreferredSize(new java.awt.Dimension(160, 23));

        jLabel17.setText("Nacionalidad actual");

        nacioAcP.setPreferredSize(new java.awt.Dimension(160, 23));

        jLabel18.setText("Domicilio");

        domP.setPreferredSize(new java.awt.Dimension(269, 23));

        campoFNP.setDateFormatString("dd/MM/yyyy");

        jLabel30.setText("Nacimiento");

        javax.swing.GroupLayout containerDataPadreLayout = new javax.swing.GroupLayout(containerDataPadre);
        containerDataPadre.setLayout(containerDataPadreLayout);
        containerDataPadreLayout.setHorizontalGroup(
            containerDataPadreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerDataPadreLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(containerDataPadreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(containerDataPadreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(containerDataPadreLayout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(campoNomP, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(campoApePadre1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(containerDataPadreLayout.createSequentialGroup()
                            .addGroup(containerDataPadreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, containerDataPadreLayout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(comboEcNacP, 0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(containerDataPadreLayout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addGap(18, 18, 18)
                                    .addComponent(campoPP, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(containerDataPadreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(containerDataPadreLayout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(campoMP, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(containerDataPadreLayout.createSequentialGroup()
                                    .addComponent(jLabel14)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(comboEcAcP, 0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel15)))))
                    .addGroup(containerDataPadreLayout.createSequentialGroup()
                        .addGroup(containerDataPadreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(containerDataPadreLayout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(domP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, containerDataPadreLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nacioNacP, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel17)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(containerDataPadreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(containerDataPadreLayout.createSequentialGroup()
                        .addGroup(containerDataPadreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel30))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(containerDataPadreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(containerDataPadreLayout.createSequentialGroup()
                                .addComponent(campoFNP, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(campoNacP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(containerDataPadreLayout.createSequentialGroup()
                        .addGroup(containerDataPadreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nacioAcP, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(containerDataPadreLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campoApePadre2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        containerDataPadreLayout.setVerticalGroup(
            containerDataPadreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerDataPadreLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(containerDataPadreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(campoNomP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(campoApePadre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(campoApePadre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(containerDataPadreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(campoPP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(campoMP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(campoNacP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(containerDataPadreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(containerDataPadreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(comboEcNacP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14)
                        .addComponent(comboEcAcP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15)
                        .addComponent(jLabel30))
                    .addComponent(campoFNP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(containerDataPadreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(nacioNacP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(nacioAcP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(containerDataPadreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(domP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        containerDataMadre.setBorder(javax.swing.BorderFactory.createTitledBorder("Madre"));
        containerDataMadre.setPreferredSize(new java.awt.Dimension(789, 170));

        jLabel19.setText("Nombre");

        campoNomM.setPreferredSize(new java.awt.Dimension(160, 23));

        jLabel20.setText("Apellido 1");

        campoApeMadre.setPreferredSize(new java.awt.Dimension(160, 23));

        jLabel21.setText("Apellido 2");

        campoApeMadre2.setPreferredSize(new java.awt.Dimension(160, 23));

        jLabel22.setText("Padre");

        campoPM.setPreferredSize(new java.awt.Dimension(160, 23));

        jLabel23.setText("Madre");

        campoMM.setPreferredSize(new java.awt.Dimension(160, 23));

        jLabel24.setText("Nacido en");

        campoNacM.setPreferredSize(new java.awt.Dimension(245, 23));

        jLabel25.setText("E.C al nacer el hijo");

        comboEcNacM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Soltera", "Casada", "Divorciada", "Viuda" }));
        comboEcNacM.setPreferredSize(new java.awt.Dimension(96, 23));

        jLabel26.setText("E.C actual");

        comboEcAcM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Soltera", "Casada", "Divorciada", "Viuda", "Fallecida" }));
        comboEcAcM.setPreferredSize(new java.awt.Dimension(96, 23));

        jLabel28.setText("Nacionalidad al nacer el hijo");

        nacioNacM.setPreferredSize(new java.awt.Dimension(160, 23));

        jLabel29.setText("Nacionalidad actual");

        nacioAcM.setPreferredSize(new java.awt.Dimension(160, 23));

        campoFNM.setDateFormatString("dd/MM/yyyy");
        campoFNM.setPreferredSize(new java.awt.Dimension(150, 23));

        jLabel31.setText("Nacimiento");

        javax.swing.GroupLayout containerDataMadreLayout = new javax.swing.GroupLayout(containerDataMadre);
        containerDataMadre.setLayout(containerDataMadreLayout);
        containerDataMadreLayout.setHorizontalGroup(
            containerDataMadreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerDataMadreLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(containerDataMadreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(containerDataMadreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(containerDataMadreLayout.createSequentialGroup()
                            .addComponent(jLabel19)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(campoNomM, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel20)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(campoApeMadre, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(containerDataMadreLayout.createSequentialGroup()
                            .addGroup(containerDataMadreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, containerDataMadreLayout.createSequentialGroup()
                                    .addComponent(jLabel25)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(comboEcNacM, 0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(containerDataMadreLayout.createSequentialGroup()
                                    .addComponent(jLabel22)
                                    .addGap(18, 18, 18)
                                    .addComponent(campoPM, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(containerDataMadreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(containerDataMadreLayout.createSequentialGroup()
                                    .addComponent(jLabel23)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(campoMM, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(containerDataMadreLayout.createSequentialGroup()
                                    .addComponent(jLabel26)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(comboEcAcM, 0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel27)))))
                    .addGroup(containerDataMadreLayout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nacioNacM, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel29)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(containerDataMadreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(containerDataMadreLayout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campoNacM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(containerDataMadreLayout.createSequentialGroup()
                        .addGroup(containerDataMadreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nacioAcM, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(containerDataMadreLayout.createSequentialGroup()
                                .addComponent(jLabel31)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoFNM, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(containerDataMadreLayout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campoApeMadre2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        containerDataMadreLayout.setVerticalGroup(
            containerDataMadreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerDataMadreLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(containerDataMadreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(campoNomM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(campoApeMadre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(campoApeMadre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(containerDataMadreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(campoPM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(campoMM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(campoNacM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(containerDataMadreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(containerDataMadreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel25)
                        .addComponent(comboEcNacM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel26)
                        .addComponent(comboEcAcM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel27))
                    .addComponent(jLabel31)
                    .addComponent(campoFNM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(containerDataMadreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(nacioNacM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29)
                    .addComponent(nacioAcM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlProgenitoresLayout = new javax.swing.GroupLayout(pnlProgenitores);
        pnlProgenitores.setLayout(pnlProgenitoresLayout);
        pnlProgenitoresLayout.setHorizontalGroup(
            pnlProgenitoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProgenitoresLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(pnlProgenitoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(containerDataPadre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(containerDataMadre, javax.swing.GroupLayout.DEFAULT_SIZE, 812, Short.MAX_VALUE))
                .addGap(16, 16, 16))
        );
        pnlProgenitoresLayout.setVerticalGroup(
            pnlProgenitoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProgenitoresLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(containerDataPadre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(containerDataMadre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Datos Progenitores", pnlProgenitores);

        labelCheck30.setText("¿Padres Casados?");

        combo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SI", "NO" }));
        combo1.setPreferredSize(new java.awt.Dimension(90, 23));

        jLabel32.setText("Fecha Celebracion");

        fechaMatri.setDateFormatString("dd/MM/yyyy");
        fechaMatri.setPreferredSize(new java.awt.Dimension(150, 23));

        lblLugar.setText("Lugar");

        campoLugar.setPreferredSize(new java.awt.Dimension(200, 23));

        lblLugar1.setText("Inscrito en");

        inscripcion.setPreferredSize(new java.awt.Dimension(200, 23));

        javax.swing.GroupLayout pnlNacimiento1Layout = new javax.swing.GroupLayout(pnlNacimiento1);
        pnlNacimiento1.setLayout(pnlNacimiento1Layout);
        pnlNacimiento1Layout.setHorizontalGroup(
            pnlNacimiento1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNacimiento1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlNacimiento1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlNacimiento1Layout.createSequentialGroup()
                        .addComponent(labelCheck30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(combo1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fechaMatri, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblLugar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campoLugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlNacimiento1Layout.createSequentialGroup()
                        .addComponent(lblLugar1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(inscripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        pnlNacimiento1Layout.setVerticalGroup(
            pnlNacimiento1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNacimiento1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(pnlNacimiento1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlNacimiento1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblLugar)
                        .addComponent(campoLugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(fechaMatri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlNacimiento1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelCheck30)
                        .addComponent(combo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel32)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlNacimiento1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLugar1)
                    .addComponent(inscripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(441, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Datos del Matrimonio", pnlNacimiento1);

        labelCheck2.setText("Nombre Contacto 1");

        campoNC.setPreferredSize(new java.awt.Dimension(220, 23));

        labelCheck3.setText("Direccion Contacto 1");

        campoDC1.setPreferredSize(new java.awt.Dimension(220, 23));

        labelCheck4.setText("Telefono Contacto 1");

        campoTC1.setText("+54 9");
        campoTC1.setPreferredSize(new java.awt.Dimension(220, 23));

        labelCheck5.setText("Nombre Contacto 2");

        campoNC2.setPreferredSize(new java.awt.Dimension(220, 23));

        labelCheck6.setText("Direccion Contacto 2");

        campoDC2.setPreferredSize(new java.awt.Dimension(220, 23));

        labelCheck7.setText("Telefono Contacto 2");

        campoTC2.setText("+54 9");
        campoTC2.setPreferredSize(new java.awt.Dimension(220, 23));

        labelCheck8.setText("Conyuge/Pareja");

        campoCony.setPreferredSize(new java.awt.Dimension(220, 23));

        javax.swing.GroupLayout pnlContactoLayout = new javax.swing.GroupLayout(pnlContacto);
        pnlContacto.setLayout(pnlContactoLayout);
        pnlContactoLayout.setHorizontalGroup(
            pnlContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContactoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(pnlContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlContactoLayout.createSequentialGroup()
                        .addComponent(labelCheck8)
                        .addGap(41, 41, 41)
                        .addComponent(campoCony, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlContactoLayout.createSequentialGroup()
                        .addComponent(labelCheck7)
                        .addGap(18, 18, 18)
                        .addComponent(campoTC2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlContactoLayout.createSequentialGroup()
                        .addComponent(labelCheck6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campoDC2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlContactoLayout.createSequentialGroup()
                        .addGroup(pnlContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelCheck2)
                            .addComponent(labelCheck3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(campoDC1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoNC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlContactoLayout.createSequentialGroup()
                        .addGroup(pnlContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelCheck4)
                            .addComponent(labelCheck5))
                        .addGap(18, 18, 18)
                        .addGroup(pnlContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoTC1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoNC2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(426, 471, Short.MAX_VALUE))
        );
        pnlContactoLayout.setVerticalGroup(
            pnlContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContactoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pnlContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCheck2)
                    .addComponent(campoNC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCheck3)
                    .addComponent(campoDC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCheck4)
                    .addComponent(campoTC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCheck5)
                    .addComponent(campoNC2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCheck6)
                    .addComponent(campoDC2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCheck7)
                    .addComponent(campoTC2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCheck8)
                    .addComponent(campoCony, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(260, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Contactos", pnlContacto);

        labelCheck9.setText("Nombre Hijo 1");

        campoNH1.setPreferredSize(new java.awt.Dimension(220, 23));

        labelCheck10.setText("Lugar de Nacimiento Hijo 1");

        campoLNH1.setPreferredSize(new java.awt.Dimension(220, 23));

        labelCheck11.setText("Fecha de Nacimiento Hijo 1");

        campoFNH1.setDateFormatString("dd/MM/yyyy");

        campoNH2.setPreferredSize(new java.awt.Dimension(220, 23));

        labelCheck16.setText("Nombre Hijo 2");

        labelCheck17.setText("Lugar de Nacimiento Hijo 2");

        campoLNH2.setPreferredSize(new java.awt.Dimension(220, 23));

        campoFNH2.setDateFormatString("dd/MM/yyyy");

        labelCheck18.setText("Fecha de Nacimiento Hijo 2");

        labelCheck19.setText("Nombre Hijo 3");

        campoNH3.setPreferredSize(new java.awt.Dimension(220, 23));

        campoLNH3.setPreferredSize(new java.awt.Dimension(220, 23));

        labelCheck20.setText("Lugar de Nacimiento Hijo 3");

        labelCheck21.setText("Fecha de Nacimiento Hijo 3");

        campoFNH3.setDateFormatString("dd/MM/yyyy");

        labelCheck22.setText("Nombre Hijo 4");

        campoNH4.setPreferredSize(new java.awt.Dimension(220, 23));

        labelCheck23.setText("Lugar de Nacimiento Hijo 4");

        campoLNH4.setPreferredSize(new java.awt.Dimension(220, 23));

        campoFNH4.setDateFormatString("dd/MM/yyyy");

        labelCheck24.setText("Fecha de Nacimiento Hijo 4");

        labelCheck25.setText("Nombre Hijo 5");

        campoNH5.setPreferredSize(new java.awt.Dimension(220, 23));

        labelCheck26.setText("Lugar de Nacimiento Hijo 5");

        campoLNH5.setPreferredSize(new java.awt.Dimension(220, 23));

        labelCheck27.setText("Fecha de Nacimiento Hijo 5");

        campoFNH5.setDateFormatString("dd/MM/yyyy");

        javax.swing.GroupLayout pnlHijosLayout = new javax.swing.GroupLayout(pnlHijos);
        pnlHijos.setLayout(pnlHijosLayout);
        pnlHijosLayout.setHorizontalGroup(
            pnlHijosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHijosLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(pnlHijosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlHijosLayout.createSequentialGroup()
                        .addGroup(pnlHijosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelCheck19)
                            .addComponent(labelCheck20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlHijosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(campoLNH3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoNH3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlHijosLayout.createSequentialGroup()
                        .addComponent(labelCheck21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoFNH3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlHijosLayout.createSequentialGroup()
                        .addGroup(pnlHijosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlHijosLayout.createSequentialGroup()
                                .addGroup(pnlHijosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelCheck9)
                                    .addComponent(labelCheck10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlHijosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(campoLNH1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(campoNH1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnlHijosLayout.createSequentialGroup()
                                .addComponent(labelCheck11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoFNH1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(pnlHijosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlHijosLayout.createSequentialGroup()
                                .addComponent(labelCheck24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campoFNH4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHijosLayout.createSequentialGroup()
                                .addGroup(pnlHijosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelCheck22)
                                    .addComponent(labelCheck23))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(pnlHijosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlHijosLayout.createSequentialGroup()
                                        .addComponent(campoNH4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(campoLNH4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(pnlHijosLayout.createSequentialGroup()
                        .addGroup(pnlHijosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlHijosLayout.createSequentialGroup()
                                .addGroup(pnlHijosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelCheck16)
                                    .addComponent(labelCheck17))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlHijosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(campoLNH2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(campoNH2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnlHijosLayout.createSequentialGroup()
                                .addComponent(labelCheck18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoFNH2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(pnlHijosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlHijosLayout.createSequentialGroup()
                                .addComponent(labelCheck25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(campoNH5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlHijosLayout.createSequentialGroup()
                                .addComponent(labelCheck26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campoLNH5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlHijosLayout.createSequentialGroup()
                                .addComponent(labelCheck27)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoFNH5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(15, 15, 15)))
                .addGap(15, 15, 15))
        );
        pnlHijosLayout.setVerticalGroup(
            pnlHijosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHijosLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pnlHijosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCheck9)
                    .addComponent(campoNH1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCheck22)
                    .addComponent(campoNH4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlHijosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCheck10)
                    .addComponent(campoLNH1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCheck23)
                    .addComponent(campoLNH4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlHijosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCheck11)
                    .addComponent(campoFNH1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCheck24)
                    .addComponent(campoFNH4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlHijosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlHijosLayout.createSequentialGroup()
                        .addGroup(pnlHijosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelCheck16)
                            .addComponent(campoNH2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlHijosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelCheck17)
                            .addComponent(campoLNH2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlHijosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelCheck18)
                            .addComponent(campoFNH2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlHijosLayout.createSequentialGroup()
                        .addGroup(pnlHijosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelCheck25)
                            .addComponent(campoNH5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlHijosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelCheck26)
                            .addComponent(campoLNH5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlHijosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelCheck27)
                            .addComponent(campoFNH5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlHijosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCheck19)
                    .addComponent(campoNH3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlHijosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCheck20)
                    .addComponent(campoLNH3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlHijosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCheck21)
                    .addComponent(campoFNH3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(190, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Hijos", pnlHijos);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFin;
    public javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField campoA1;
    private javax.swing.JTextField campoA2;
    public javax.swing.JTextField campoApeMadre;
    public javax.swing.JTextField campoApeMadre2;
    public javax.swing.JTextField campoApePadre1;
    public javax.swing.JTextField campoApePadre2;
    private javax.swing.JTextField campoCN;
    public javax.swing.JTextField campoCP;
    private javax.swing.JTextField campoCalle;
    private javax.swing.JTextField campoCiudad;
    private javax.swing.JTextField campoConsulado;
    public javax.swing.JTextField campoCony;
    public javax.swing.JTextField campoDC1;
    public javax.swing.JTextField campoDC2;
    private javax.swing.JTextField campoDNI;
    private javax.swing.JTextField campoEmail;
    public com.toedter.calendar.JDateChooser campoFI;
    private com.toedter.calendar.JDateChooser campoFN;
    public com.toedter.calendar.JDateChooser campoFNH1;
    public com.toedter.calendar.JDateChooser campoFNH2;
    public com.toedter.calendar.JDateChooser campoFNH3;
    public com.toedter.calendar.JDateChooser campoFNH4;
    public com.toedter.calendar.JDateChooser campoFNH5;
    public com.toedter.calendar.JDateChooser campoFNM;
    public com.toedter.calendar.JDateChooser campoFNP;
    public com.toedter.calendar.JDateChooser campoFT;
    public javax.swing.JTextField campoHN;
    public javax.swing.JTextField campoLNH1;
    public javax.swing.JTextField campoLNH2;
    public javax.swing.JTextField campoLNH3;
    public javax.swing.JTextField campoLNH4;
    public javax.swing.JTextField campoLNH5;
    public javax.swing.JTextField campoLugar;
    public javax.swing.JTextField campoME;
    public javax.swing.JTextField campoMM;
    public javax.swing.JTextField campoMP;
    public javax.swing.JTextField campoNC;
    public javax.swing.JTextField campoNC2;
    public javax.swing.JTextField campoNH1;
    public javax.swing.JTextField campoNH2;
    public javax.swing.JTextField campoNH3;
    public javax.swing.JTextField campoNH4;
    public javax.swing.JTextField campoNH5;
    public javax.swing.JTextField campoNacM;
    public javax.swing.JTextField campoNacP;
    private javax.swing.JTextField campoNacio;
    public javax.swing.JTextField campoNomM;
    public javax.swing.JTextField campoNomP;
    private javax.swing.JTextField campoNombres;
    public javax.swing.JTextField campoNroPag;
    public javax.swing.JTextField campoPE;
    public javax.swing.JTextField campoPM;
    public javax.swing.JTextField campoPN;
    public javax.swing.JTextField campoPP;
    public javax.swing.JTextField campoPagina;
    private javax.swing.JTextField campoPais;
    private javax.swing.JTextField campoPrN;
    private javax.swing.JTextField campoProvincia;
    public javax.swing.JTextField campoRC;
    public javax.swing.JTextField campoTC1;
    public javax.swing.JTextField campoTC2;
    private javax.swing.JTextField campoTelefono;
    public javax.swing.JTextField campoTomo;
    public javax.swing.JComboBox<String> combo1;
    public javax.swing.JComboBox<String> comboEC;
    public javax.swing.JComboBox<String> comboEcAcM;
    public javax.swing.JComboBox<String> comboEcAcP;
    public javax.swing.JComboBox<String> comboEcNacM;
    public javax.swing.JComboBox<String> comboEcNacP;
    public javax.swing.JComboBox<String> comboEstudios;
    public javax.swing.JComboBox<String> comboSx;
    private javax.swing.JPanel containerDataMadre;
    private javax.swing.JPanel containerDataPadre;
    public javax.swing.JTextField domP;
    public com.toedter.calendar.JDateChooser fechaMatri;
    public javax.swing.JTextField inscripcion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel labelCheck10;
    private javax.swing.JLabel labelCheck11;
    private javax.swing.JLabel labelCheck12;
    private javax.swing.JLabel labelCheck13;
    private javax.swing.JLabel labelCheck14;
    private javax.swing.JLabel labelCheck16;
    private javax.swing.JLabel labelCheck17;
    private javax.swing.JLabel labelCheck18;
    private javax.swing.JLabel labelCheck19;
    private javax.swing.JLabel labelCheck2;
    private javax.swing.JLabel labelCheck20;
    private javax.swing.JLabel labelCheck21;
    private javax.swing.JLabel labelCheck22;
    private javax.swing.JLabel labelCheck23;
    private javax.swing.JLabel labelCheck24;
    private javax.swing.JLabel labelCheck25;
    private javax.swing.JLabel labelCheck26;
    private javax.swing.JLabel labelCheck27;
    private javax.swing.JLabel labelCheck3;
    private javax.swing.JLabel labelCheck30;
    private javax.swing.JLabel labelCheck4;
    private javax.swing.JLabel labelCheck5;
    private javax.swing.JLabel labelCheck6;
    private javax.swing.JLabel labelCheck7;
    private javax.swing.JLabel labelCheck8;
    private javax.swing.JLabel labelCheck9;
    private javax.swing.JLabel labelFn;
    private javax.swing.JLabel labelFn1;
    private javax.swing.JLabel lblA1;
    private javax.swing.JLabel lblA2;
    private javax.swing.JLabel lblCN;
    private javax.swing.JLabel lblCalle;
    private javax.swing.JLabel lblCiudad;
    private javax.swing.JLabel lblConsulado;
    private javax.swing.JLabel lblDNI;
    private javax.swing.JLabel lblEC;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblLugar;
    private javax.swing.JLabel lblLugar1;
    private javax.swing.JLabel lblME;
    private javax.swing.JLabel lblNacio;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNro;
    private javax.swing.JLabel lblPN;
    private javax.swing.JLabel lblPais;
    private javax.swing.JLabel lblPrN;
    private javax.swing.JLabel lblProvincia;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel logoEmpresa;
    public javax.swing.JTextField nacioAcM;
    public javax.swing.JTextField nacioAcP;
    public javax.swing.JTextField nacioNacM;
    public javax.swing.JTextField nacioNacP;
    private javax.swing.JPanel pnlCentral;
    private javax.swing.JPanel pnlContacto;
    private javax.swing.JPanel pnlHijos;
    private javax.swing.JPanel pnlNacimiento;
    private javax.swing.JPanel pnlNacimiento1;
    private javax.swing.JPanel pnlProgenitores;
    private javax.swing.JPanel pnlSuperior;
    private javax.swing.JLabel txtPnlSuperior;
    // End of variables declaration//GEN-END:variables
}
